name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the repository
        uses: actions/checkout@master
      - name: Update the Gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 80c4cf9a0877a2ec5aeca05d8cac0f29
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
